name: tuievolution_chess
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # --- FRONTEND PAKETLERİ ---
  flutter_svg: ^2.2.4
  google_fonts: ^8.0.2
  graphview: ^1.5.1
  flutter_chess_board: ^1.0.1

  # --- BACKEND PAKETLERİ ---
  supabase_flutter: ^2.4.0  # Veritabanı ve kimlik doğrulama işlemleri için
  flutter_dotenv: ^6.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Veri setini uygulamanın içine dahil ediyoruz
  assets:
    - .env